Update byobu plugin to r1787 (4.50 pre-release).

diff --git a/plugins/byobu/bin/byobu-janitor b/plugins/byobu/bin/byobu-janitor
--- a/plugins/byobu/bin/byobu-janitor
+++ b/plugins/byobu/bin/byobu-janitor
@@ -21,7 +21,7 @@
 
 PKG="byobu"
 [ -z "${BYOBU_PREFIX}" ] && export BYOBU_PREFIX="/home/daniel/.dotfiles/oh-my-zsh/plugins/byobu"
-. "${BYOBU_PREFIX}/lib/${PKG}/.common"
+. "${BYOBU_PREFIX}/lib/${PKG}/include/common"
 
 # Ensure that all updates get run immediately
 rm -rf "$BYOBU_RUN_DIR/.last.$BYOBU_BACKEND"
@@ -46,22 +46,29 @@ if [ -d "$BYOBU_CONFIG_DIR" ] && [ ! -w "$BYOBU_CONFIG_DIR" ]; then
 	exit 1
 fi
 
+# Affects: Upgrades from <= byobu 4.30
+# Clear out old style status configuration
+if ! grep -qs "^screen_upper_left=" "$BYOBU_CONFIG_DIR/status"; then
+	rm -f "$BYOBU_CONFIG_DIR/status" "$BYOBU_CONFIG_DIR/statusrc"
+fi
+
 # Affects: First runs with no configuration
 # Seed the configuration
 # Setup initial local user configuration
 [ -r "$BYOBU_CONFIG_DIR/color" ] || printf "BACKGROUND=k\nFOREGROUND=w\nMONOCHROME=0" > "$BYOBU_CONFIG_DIR/color"
-[ -r "$BYOBU_CONFIG_DIR/profile" ] || echo "source $BYOBU_PREFIX/share/$PKG/profiles/common" > "$BYOBU_CONFIG_DIR/profile"
-[ -r "$BYOBU_CONFIG_DIR/profile.tmux" ] || echo "source-file $BYOBU_PREFIX/share/$PKG/profiles/tmux" > "$BYOBU_CONFIG_DIR/profile.tmux"
-[ -r "$BYOBU_CONFIG_DIR/keybindings" ] || echo "source $BYOBU_PREFIX/share/$PKG/keybindings/common" > "$BYOBU_CONFIG_DIR/keybindings"
+[ -r "$BYOBU_CONFIG_DIR/profile" ] || echo "source \$BYOBU_PREFIX/share/$PKG/profiles/common" > "$BYOBU_CONFIG_DIR/profile"
+[ -r "$BYOBU_CONFIG_DIR/profile.tmux" ] || echo "source \$BYOBU_PREFIX/share/$PKG/profiles/tmux" > "$BYOBU_CONFIG_DIR/profile.tmux"
+[ -r "$BYOBU_CONFIG_DIR/keybindings" ] || echo "source \$BYOBU_PREFIX/share/$PKG/keybindings/common" > "$BYOBU_CONFIG_DIR/keybindings"
 [ -r "$BYOBU_CONFIG_DIR/windows" ] || touch "$BYOBU_CONFIG_DIR/windows"
 [ -r "$HOME/.screenrc" ] || touch "$HOME/.screenrc"
+[ -r "$BYOBU_CONFIG_DIR/.tmux.conf" ] || touch "$BYOBU_CONFIG_DIR/.tmux.conf"
 for f in status statusrc; do
 	if [ ! -r "$BYOBU_CONFIG_DIR/$f" ]; then
 		# Copy from skeleton, if possible
 		cp -f "$BYOBU_PREFIX/share/$PKG/status/$f" "$BYOBU_CONFIG_DIR/$f"
-		if [ "$f" = "status" ] && metadata_available; then
-			# Enable ec2_cost if we're in ec2
-			$SED -i -e "s/ec2_cost=.*/ec2_cost=1/" "$BYOBU_CONFIG_DIR/$f"
+		# Enable ec2_cost, if we're in ec2 and seeding a new setup
+		if metadata_available; then
+			$SED -i -e "s/#ec2_cost/ec2_cost/g" "$BYOBU_CONFIG_DIR/$f"
 		fi
 	fi
 done
@@ -127,7 +134,7 @@ fi
 # Affects: Upgrades from <= byobu 4.22
 killall -u $USER byobu-statusd >/dev/null 2>&1 || true
 
-# Clean up flag
-rm -f "$FLAG"
+# Clean up flag (new and old)
+rm -f "$FLAG" "/var/run/screen/S-$USER/$PKG.reload-required"
 
 # vi: syntax=sh ts=4 noexpandtab
